DHallPicker/Controllers/PickerController.cs
using System.Web.Mvc;
using DHallPicker.Data.Repositories;
using DHallPicker.Models;
using DHallPicker.Models.Models;
using DHallPicker.Operations.Operations;

namespace DHallPicker.Controllers
{
    public class PickerController : Controller
    {
        //
        // GET: /Picker/AllMenus
        public ActionResult AllMenus()
        {
            DiningHallLookupResult nicelySortedData = new DiningHallLookupResult();
            nicelySortedData.MenuData = new DiningHallRepository().SelectAllHalls();

            DishRepository dataContext = new DishRepository();

            if (dataContext.CheckIfTodayInDatabase(nicelySortedData) == false)
                new WebScraper().Run();

            nicelySortedData = dataContext.SelectAllDishes(nicelySortedData);

            return View(nicelySortedData);
        }

        //
        // GET: /Picker/SelectFilters
        public ActionResult SelectFilters()
        {
            return View(new DietWrapper());
        }

        [HttpPost]
        public ActionResult SelectFilters(DietWrapper currentModel, int[] diets)
        {
            DiningHallLookupResult nicelySortedData = new DiningHallLookupResult();
            nicelySortedData.MenuData = new DiningHallRepository().SelectAllHalls();

            DishRepository dataContext = new DishRepository();

            if (dataContext.CheckIfTodayInDatabase(nicelySortedData) == false)
                new WebScraper().Run();

            nicelySortedData = dataContext.SelectAllDishes(nicelySortedData);

            MenuFilter filterOps = new MenuFilter();
            nicelySortedData = filterOps.GetFilteredMenus(nicelySortedData, diets);
            nicelySortedData = filterOps.GetRecommendations(nicelySortedData);
            
            return View("FilteredMenu", nicelySortedData);
        }
    }
}

DHallPicker/Views/Picker/AllMenus.cshtml
@model DHallPicker.Models.Models.DiningHallLookupResult

@using DHallPicker.Models.Models

@{
    ViewBag.Title = "All Menus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container allmenus-container">
    <div class="row">
        <div class="col-lg-4">
            <h3 class="meal">Breakfast</h3>
            <div class="panel-group" id="accordion" data-collapse-type="manual">
                <div class="panel panel-default">
                    @foreach (DiningHall dHall in Model.MenuData)
                    {
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                @Html.Raw("<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse" + @dHall.DiningHallID + "\">")
                                @dHall.DiningHallName
                                @Html.Raw("</a>")
                            </h4>
                        </div>
                        @Html.Raw("<div id=\"collapse" + @dHall.DiningHallID + "\" class=\"panel-collapse collapse in\">")
                        <div class="panel-body">
                            @foreach (Dish currentDish in dHall.Breakfast)
                            {
                                <div>@currentDish.DishName</div>
                            }
                        </div>
                        @Html.Raw("</div>")
                    }
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <h3 class="meal">Lunch</h3>
            <div class="panel-group" id="accordion2" data-collapse-type="manual">
                <div class="panel panel-default">
                    @foreach (DiningHall dHall in Model.MenuData)
                    {
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                @Html.Raw("<a data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#2collapse" + @dHall.DiningHallID + "\">")
                                @dHall.DiningHallName
                                @Html.Raw("</a>")
                            </h4>
                        </div>
                        @Html.Raw("<div id=\"2collapse" + @dHall.DiningHallID + "\" class=\"panel-collapse collapse in\">")
                        <div class="panel-body">
                            @foreach (Dish currentDish in dHall.Lunch)
                            {
                                <div>@currentDish.DishName</div>
                            }
                        </div>
                        @Html.Raw("</div>")
                    }
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <h3 class="meal">Dinner</h3>
            <div class="panel-group" id="accordion3" data-collapse-type="manual">
                <div class="panel panel-default">
                    @foreach (DiningHall dHall in Model.MenuData)
                    {
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                @Html.Raw("<a data-toggle=\"collapse\" data-parent=\"#accordion3\" href=\"#3collapse" + @dHall.DiningHallID + "\">")
                                @dHall.DiningHallName
                                @Html.Raw("</a>")
                            </h4>
                        </div>
                        @Html.Raw("<div id=\"3collapse" + @dHall.DiningHallID + "\" class=\"panel-collapse collapse in\">")
                        <div class="panel-body">
                            @foreach (Dish currentDish in dHall.Dinner)
                            {
                                <div>@currentDish.DishName</div>
                            }
                        </div>
                        @Html.Raw("</div>")
                    }
                </div>
            </div>
        </div>
    </div>
</div>

DHallPicker/Views/Picker/FilteredMenu.cshtml
@model DHallPicker.Models.Models.DiningHallLookupResult

@using DHallPicker.Models.Models

@{
    ViewBag.Title = "Your Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container allmenus-container">
    <div class="row">
        <div class="col-lg-4">
            <h3 class="meal">Breakfast</h3>
            <p class="recommended">Recommended: @Model.RecommendedBreakfast</p>
            <div class="panel-group" id="accordion" data-collapse-type="manual">
                <div class="panel panel-default">
                    @foreach (DiningHall dHall in Model.MenuData)
                    {
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                @Html.Raw("<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse" + @dHall.DiningHallID + "\">")
                                @dHall.DiningHallName
                                @Html.Raw("</a>")
                            </h4>
                        </div>
                        @Html.Raw("<div id=\"collapse" + @dHall.DiningHallID + "\" class=\"panel-collapse collapse in\">")
                        <div class="panel-body">
                            @foreach (Dish currentDish in dHall.Breakfast)
                            {
                                <div>@Html.Raw(currentDish.DishName)</div>
                            }
                        </div>
                        @Html.Raw("</div>")
                    }
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <h3 class="meal">Lunch</h3>
            <p class="recommended">Recommended: @Model.RecommendedLunch</p>
            <div class="panel-group" id="accordion2" data-collapse-type="manual">
                <div class="panel panel-default">
                    @foreach (DiningHall dHall in Model.MenuData)
                    {
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                @Html.Raw("<a data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#2collapse" + @dHall.DiningHallID + "\">")
                                @dHall.DiningHallName
                                @Html.Raw("</a>")
                            </h4>
                        </div>
                        @Html.Raw("<div id=\"2collapse" + @dHall.DiningHallID + "\" class=\"panel-collapse collapse in\">")
                        <div class="panel-body">
                            @foreach (Dish currentDish in dHall.Lunch)
                            {
                                <div>@currentDish.DishName</div>
                            }
                        </div>
                        @Html.Raw("</div>")
                    }
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <h3 class="meal">Dinner</h3>
            <p class="recommended">Recommended: @Model.RecommendedDinner</p>
            <div class="panel-group" id="accordion3" data-collapse-type="manual">
                <div class="panel panel-default">
                    @foreach (DiningHall dHall in Model.MenuData)
                    {
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                @Html.Raw("<a data-toggle=\"collapse\" data-parent=\"#accordion3\" href=\"#3collapse" + @dHall.DiningHallID + "\">")
                                @dHall.DiningHallName
                                @Html.Raw("</a>")
                            </h4>
                        </div>
                        @Html.Raw("<div id=\"3collapse" + @dHall.DiningHallID + "\" class=\"panel-collapse collapse in\">")
                        <div class="panel-body">
                            @foreach (Dish currentDish in dHall.Dinner)
                            {
                                <div>@currentDish.DishName</div>
                            }
                        </div>
                        @Html.Raw("</div>")
                    }
                </div>
            </div>
        </div>
    </div>
</div>

DHallPicker/Views/Picker/SelectFilters.cshtml
@using DHallPicker.Models.Models
@model DHallPicker.Models.DietWrapper

@{
    ViewBag.Title = "Select Filters";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container allmenus-container">
    <h2>Select Filters</h2>
    @using (Html.BeginForm("SelectFilters", "Picker", FormMethod.Post, new { id = "filter-form" }))
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <td></td>
                    <td>Preference</td>
                    <td>Description</td>
                </tr>
            </thead>
            <tbody>
                @foreach (Diet filter in Model.AllFilters)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="diets" value="@filter.DishFilterID"/></td>
                        <td>@filter.FilterName</td>
                        <td>@filter.FilterDescription</td>
                    </tr>
                }

            </tbody>
        </table>
        <input type="submit" value="Pick a Dining Hall!" class="btn btn-primary" />
    }
</div>

@section ViewScripts
{
    <script>
        function onSubmit() {
            var fields = $("input[name='diets']").serializeArray();
            
            if (fields.length == 0) {
                alert('Please select at least one filter.');
                return false;
            }
        }

        $('#filter-form').submit(onSubmit);
    </script>
}